# Generated by Django 5.2.3 on 2025-07-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('publication_year', models.DateField()),
                ('isAvailable', models.BooleanField(default=False)),
                ('rental_fee', models.FloatField(default=0.0)),
            ],
        ),
    ]
