# Generated by Django 5.2.4 on 2025-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isAvailable',
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrowed_books', models.ManyToManyField(blank=True, related_name='borrowers', to='books.book')),
                ('notifications', models.ManyToManyField(blank=True, related_name='recipients', to='books.notification')),
            ],
        ),
    ]
